name: macOS

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            setup-python: 'false'
            modules: 'qtcharts qtwebengine'
        
      - name: Build kleiner-brauhelfer-2
        run: |
          chmod +x ./build_macos.sh
          ./build_macos.sh "${Qt5_DIR}/bin/" "-${{ github.sha }}"
          mkdir deploy
          cp build-macos/bin/kbh2_*.zip deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: kleiner-brauhelfer-2
          path: deploy
